function SwitJS(){}SwitJS.BOOT_FILE="js/game.js";SwitJS.isIE=!1;SwitJS.browserVersion=0;SwitJS.browserName="";SwitJS.platformVersion=0;SwitJS.isLowDevice=!1;SwitJS.useAssetsSD=!1;SwitJS.isSupported=!1;SwitJS.debug=!1;SwitJS.isMobileDevice=!1;SwitJS.isPhone=!1;SwitJS.iDevice=!1;SwitJS.deviceModel="";SwitJS.userAgent="";SwitJS.include=function(a){document.write('<script type="text/javascript" language="javascript" src="'+a+'">\x3c/script>')};
SwitJS.test=function(){if("undefined"===typeof window.SwitEntryFiles||!0===window.SWT_ADVANCED)SwitJS.include(SwitJS.BOOT_FILE);else{for(var a=window.SwitEntryFiles,b=0;b<a.length;b++)SwitJS.include(a[b]);SwitJS.debug=!0}};SwitJS.start=function(){SwitJS.include(SwitJS.BOOT_FILE)};
SwitJS.setEntry=function(){SwitJS.detectBrowser(navigator);"supported"!==(SwitJS.isMobileDevice?"supported":SwitJS.isBrowserSupported())?(SwitJS.isSupported=!1,window.location="unsupported.html"+window.location.search):SwitJS.isSupported=!0};
SwitJS.detectBrowser=function(a){SwitJS.infoBrowser={};SwitJS.infoBrowser.platformType=a.platform;SwitJS.browserName=a.appName;SwitJS.browserVersion=parseFloat(a.appVersion);SwitJS.userAgent=a.userAgent;if(-1!=a.platform.indexOf("iPhone")){if(SwitJS.iDevice=!0,SwitJS.isPhone=!0,SwitJS.isMobileDevice=!0,SwitJS.infoBrowser.platformType="iPhone",/OS (\d+_\d+)/.test(a.userAgent)){var b=RegExp.$1;b=b.replace("_",".");SwitJS.platformVersion=parseFloat(b)}}else-1!=a.platform.indexOf("iPod")?(SwitJS.iDevice=
!0,SwitJS.isPhone=!0,SwitJS.isMobileDevice=!0,SwitJS.infoBrowser.platformType="iPod",SwitJS.isLowDevice=!0,SwitJS.useAssetsSD=!0,/OS (\d+_\d+)/.test(a.userAgent)&&(b=RegExp.$1,b=b.replace("_","."),SwitJS.platformVersion=parseFloat(b))):-1!=a.platform.indexOf("iPad")?(SwitJS.iDevice=!0,SwitJS.isMobileDevice=!0,SwitJS.infoBrowser.platformType="iPad",/OS (\d+_\d+)/.test(a.userAgent)&&(b=RegExp.$1,b=b.replace("_","."),SwitJS.platformVersion=parseFloat(b))):-1!=a.userAgent.indexOf("Kindle")?(b=-1!=a.userAgent.indexOf("Kindle Fire"),
SwitJS.isMobileDevice=b,SwitJS.infoBrowser.platformType=b?"Kindle Fire":"Kindle",/Android (\d+\.\d+)/.test(a.userAgent)&&(SwitJS.platformVersion=parseFloat(RegExp.$1))):-1!=a.userAgent.indexOf("Android")?(SwitJS.isMobileDevice=!0,SwitJS.infoBrowser.platformType="Android",/Android (\d+\.\d+)/.test(a.userAgent)?SwitJS.platformVersion=parseFloat(RegExp.$1):/Android (\d+)/.test(a.userAgent)&&(SwitJS.platformVersion=parseFloat(RegExp.$1))):-1!=a.userAgent.indexOf("IEMobile")?(SwitJS.isMobileDevice=!0,
SwitJS.infoBrowser.platformType="IEMobile",/IEMobile\/(\d+\.\d+)/.test(a.userAgent)&&(SwitJS.platformVersion=parseFloat(RegExp.$1))):-1!=a.platform.indexOf("Win")?SwitJS.infoBrowser.platformType="Win":-1!=a.platform.indexOf("Mac")?(SwitJS.infoBrowser.platformType="Mac",/OS X (\d+_\d+)/.test(a.userAgent)&&(b=RegExp.$1,b=b.replace("_","."),SwitJS.platformVersion=parseFloat(b))):-1!=a.platform.indexOf("Linux")&&(SwitJS.infoBrowser.platformType="Linux");-1!=a.userAgent.indexOf("Silk")||/ KF[A-Z]{4,}/.test(a.userAgent)?
(SwitJS.browserName="Silk",SwitJS.isMobileDevice=!0,SwitJS.useAssetsSD=!0,SwitJS.isLowDevice=!0,/ KF[A-Z]{4,}/.test(a.userAgent)&&(SwitJS.deviceModel="KINDLE_FIRE"),/Silk\/(\d+\.\d+)/.test(a.userAgent)&&(SwitJS.browserVersion=parseFloat(RegExp.$1))):-1!=a.userAgent.indexOf("Firefox")?(SwitJS.browserName="Firefox",/Firefox[\/\s](\d+\.\d+)/.test(a.userAgent)&&(SwitJS.browserVersion=parseFloat(RegExp.$1))):-1!=a.userAgent.indexOf("MSIE")?(SwitJS.infoBrowser.msTouchDevice=0<a.msMaxTouchPoints,SwitJS.browserName=
"MSIE",SwitJS.isIE=!0,/MSIE (\d+\.\d+);/.test(a.userAgent)&&(SwitJS.browserVersion=parseFloat(RegExp.$1))):-1!=a.userAgent.indexOf("Opera")?(SwitJS.browserName="Opera",/Opera[\/\s](\d+\.\d+)/.test(a.userAgent)&&(SwitJS.browserVersion=parseFloat(RegExp.$1))):-1!=a.userAgent.indexOf("OPR")?(SwitJS.browserName="Opera",/OPR[\/\s](\d+\.\d+)/.test(a.userAgent)&&(SwitJS.browserVersion=parseFloat(RegExp.$1))):-1!=a.userAgent.indexOf("Chrome")?(SwitJS.browserName="Chrome",/Chrome[\/\s](\d+\.\d+)/.test(a.userAgent)&&
(SwitJS.browserVersion=parseFloat(RegExp.$1))):-1!=a.userAgent.indexOf("CriOS")?(SwitJS.browserName="Chrome",/CriOS[\/\s](\d+\.\d+)/.test(a.userAgent)&&(SwitJS.browserVersion=parseFloat(RegExp.$1))):-1!=a.userAgent.indexOf("Safari")?(SwitJS.browserName="Safari",/Version[\/\s](\d+\.\d+)/.test(a.userAgent)&&(SwitJS.browserVersion=parseFloat(RegExp.$1))):SwitJS.iDevice?SwitJS.browserName="Safari":"Netscape"==a.appName&&(b=0,null!=/Trident\/.*rv:([0-9]{1,}[.0-9]{0,})/.exec(a.userAgent)&&(b=parseFloat(RegExp.$1)),
11<=b&&(SwitJS.infoBrowser.msTouchDevice=0<a.msMaxTouchPoints,SwitJS.browserName="MSIE",SwitJS.isIE=!0,SwitJS.browserVersion=b));-1!=a.userAgent.indexOf("WebKit")?SwitJS.infoBrowser.browserType="WebKit":SwitJS.infoBrowser.browserType=SwitJS.browserName;SwitJS.iDevice&&480>=screen.width&&480>=screen.height&&(SwitJS.isLowDevice=!0,SwitJS.useAssetsSD=!0);"iPad"===SwitJS.infoBrowser.platformType&&2>window.devicePixelRatio&&(SwitJS.isLowDevice=!0,SwitJS.useAssetsSD=!0);"Android"===SwitJS.infoBrowser.platformType&&
4.3>SwitJS.platformVersion&&(SwitJS.isLowDevice=!0,SwitJS.useAssetsSD=!0)};SwitJS.isBrowserSupported=function(){for(var a=window.config,b=0;b<a.browserSettings.length;b++){var c=a.browserSettings[b];if(!(c.browserType&&SwitJS.browserName!=c.browserType||c.platformType&&SwitJS.infoBrowser.platformType!=c.platformType)){if(0>c.minVersion)break;return SwitJS.browserVersion<c.minVersion?"old":"supported"}}return"unsupported"};
document.oncontextmenu=function(a){a=a||window.event;if(a.preventDefault)a.preventDefault();else return!1};document.ontouchmove=function(a){a=a||window.event;a.preventDefault()};gameStart=function(){switOnLoad()};SwitJS.setEntry();
