window['switStrings'] = {
	"STR_REP_LOADING_PRELOAD_FONT_1": {"value": "0", "locID": ""},
	"STR_REP_LOADING_PRELOAD_FONT_2": {"value": "0", "locID": ""},
	"STR_REP_LOADING_PRELOAD_FONT_3": {"value": "0", "locID": ""},
	"STR_REP_LOADING_PRELOAD_FONT_4": {"value": "0", "locID": ""},
	"STR_REP_MESSAGE_1": {"value": "1", "locID": ""},
	"STR_REP_MESSAGE_2": {"value": "2", "locID": ""},
	"STR_REP_MESSAGE_3": {"value": "3", "locID": ""},
	"STR_REP_MESSAGE_GO": {"value": "GO", "locID": ""},
	"STR_REP_POPUP_CHEATS": {"value": "CHEATS", "locID": ""},
	"STR_REP_POPUP_CHEATS_M_1": {"value": "COMPLETE MISSION 1", "locID": ""},
	"STR_REP_POPUP_CHEATS_M_2": {"value": "COMPLETE MISSION 2", "locID": ""},
	"STR_REP_POPUP_CHEATS_M_3": {"value": "COMPLETE MISSION 3", "locID": ""},
	"STR_REP_POPUP_CHEATS_COINS": {"value": "ADD COINS ( 100 )", "locID": ""},
	"STR_REP_POPUP_HELP_VERSION": {"value": "", "locID": ""},
	"STR_REP_POPUP_MISSIONS": {"value": "MISSIONS", "locID": ""},
	"STR_REP_SCREENS_SHOP_UPGRADE_INFO_1": {"value": "Makes you go faster!", "locID": "STR_REP_SCREENS_SHOP_UPGRADE_INFO_1"},
	"STR_REP_SCREENS_SHOP_UPGRADE_INFO_2": {"value": "Defeating enemies and going through rings fills your special meter faster!", "locID": "STR_REP_SCREENS_SHOP_UPGRADE_INFO_1"},
	"STR_REP_SCREENS_SHOP_UPGRADE_INFO_3": {"value": "Earn more currency from coins!", "locID": "STR_REP_SCREENS_SHOP_UPGRADE_INFO_1"},
	"STR_REP_SCREENS_SHOP_UPGRADE_INFO_4": {"value": "Increases the chance of encountering a glider drone!", "locID": "STR_REP_SCREENS_SHOP_UPGRADE_INFO_1"},
	"STR_REP_SCREENS_SHOP_UPGRADE_INFO_5": {"value": "Gives you web protection that can withstand more hits!", "locID": "STR_REP_SCREENS_SHOP_UPGRADE_INFO_1"},
	"STR_REP_SCREENS_SHOP_UPGRADE_TITLE_1": {"value": "SPEED", "locID": "STR_REP_SCREENS_SHOP_UPGRADE_TITLE_1"},
	"STR_REP_SCREENS_SHOP_UPGRADE_TITLE_2": {"value": "ACROBATICS", "locID": "STR_REP_SCREENS_SHOP_UPGRADE_TITLE_1"},
	"STR_REP_SCREENS_SHOP_UPGRADE_TITLE_3": {"value": "LUCK", "locID": "STR_REP_SCREENS_SHOP_UPGRADE_TITLE_1"},
	"STR_REP_SCREENS_SHOP_UPGRADE_TITLE_4": {"value": "DRONE", "locID": "STR_REP_SCREENS_SHOP_UPGRADE_TITLE_1"},
	"STR_REP_SCREENS_SHOP_UPGRADE_TITLE_5": {"value": "WEB SHIELD", "locID": "STR_REP_SCREENS_SHOP_UPGRADE_TITLE_1"},
	"STR_REP_POPUP_CONFIRM_INFORMATION": {"value": "Are you sure?", "locID": ""},
	"STR_REP_SHOP_TITLE": {"value": "UPGRADES", "locID": ""},
	"STR_REP_PANEL_TROPHIE_ACHIEVEMENT": {"value": "ACHIEVEMENT UNLOCKED", "locID": ""},
	"STR_REP_DIALOGUE_TAP": {"value": "-Tap to continue-", "locID": "STR_REP_DIALOGUE_TAP"},
	"STR_REP_DIALOGUE_TAP_PC": {"value": "-Click to continue-", "locID": "STR_REP_DIALOGUE_TAP"},
	"STR_REP_DIALOGUE_NAME01": {"value": "SPIDER-MAN", "locID": ""},
	"STR_REP_DIALOGUE_NAME02": {"value": "MYSTERIO", "locID": ""},
	"STR_REP_DIALOGUE_INFO_4": {"value": "Enough! Let's go!", "locID": "STR_REP_DIALOGUE_INFO1_01"},
	"STR_REP_DIALOGUE_INFO_3": {"value": "All of this... for a fight? There's something called “text message” y'know...?", "locID": "STR_REP_DIALOGUE_INFO1_01"},
	"STR_REP_DIALOGUE_INFO_2": {"value": "It's time to settle our pending business... for once!", "locID": "STR_REP_DIALOGUE_INFO1_01"},
	"STR_REP_DIALOGUE_INFO_1": {"value": "Well done, Spider-Man. This is me. The real me.", "locID": "STR_REP_DIALOGUE_INFO1_01"},
	"STR_REP_TROPHIES_TITLE": {"value": "TROPHIES", "locID": ""},
	"STR_REP_CREDITS_TITLE": {"value": "CREDITS", "locID": ""},
	"STR_REP_CREDITS_INFO_1": {"value": "Designed and developed by:", "locID": ""},
	"STR_REP_CREDITS_INFO_2": {"value": "In association with:", "locID": ""},
	"STR_REP_POPUP_HELP_TITLE": {"value": "HELP", "locID": ""},
	"STR_REP_POPUP_CONFIRM_TITLE": {"value": "CONFIRM", "locID": "STR_REP_POPUP_CONFIRM_TITLE"},
	"STR_REP_POPUP_QUIT_TITLE": {"value": "QUIT GAME", "locID": "STR_REP_POPUP_CONFIRM_TITLE"},
	"STR_REP_POPUP_ENDGAME_TEXT": {"value": "Thanks for playing!", "locID": ""},
	"STR_REP_POPUP_ENDGAME_TITLE": {"value": "CONGRATULATIONS", "locID": ""},
	"STR_REP_POPUP_RESET_TITLE": {"value": "RESET DATA", "locID": "STR_REP_POPUP_CONFIRM_TITLE"},
	"STR_REP_HUD_COINS_DATA": {"value": "#", "locID": "STR_REP_HUD_COINS_DATA"},
	"STR_REP_HUD_DISTANCE_DATA": {"value": "# m", "locID": ""},
	"STR_REP_HUD_NEW_RECORD": {"value": "NEW RECORD", "locID": ""},
	"STR_REP_HUD_COMBO_HIT": {"value": "COMBO", "locID": "STR_REP_HUD_COMBO_HIT"},
	"STR_REP_TUTORIAL_INFO_1": {"value": "Hold to start swinging. Release to let go.", "locID": "STR_REP_TUTORIAL_INFO_1"},
	"STR_REP_TUTORIAL_INFO_2": {"value": "Hit enemies to defeat them.", "locID": "STR_REP_TUTORIAL_INFO_1"},
	"STR_REP_TUTORIAL_INFO_3": {"value": "Grab these when your meter is full to perform acrobatics.", "locID": "STR_REP_TUTORIAL_INFO_1"},
	"STR_REP_TUTORIAL_INFO_4": {"value": "Tap fast to launch further!", "locID": "STR_REP_TUTORIAL_INFO_1"},
	"STR_REP_TUTORIAL_INFO_4_PC": {"value": "Click fast to launch further!", "locID": "STR_REP_TUTORIAL_INFO_1"},
	"STR_REP_TUTORIAL_INFO_5": {"value": "Hold to rise up. Release to fall down.", "locID": "STR_REP_TUTORIAL_INFO_1"},
	"STR_REP_TUTORIAL_INFO_6": {"value": "Press P to pause the game", "locID": "STR_REP_TUTORIAL_INFO_1"},
	"STR_REP_INFO_TROPHIE_6": {"value": "Defeat the real Mysterio", "locID": "STR_REP_INFO_TROPHIE_1"},
	"STR_REP_INFO_TROPHIE_5": {"value": "Rack up a 20 combo", "locID": "STR_REP_INFO_TROPHIE_1"},
	"STR_REP_INFO_TROPHIE_4": {"value": "Defeat Mysterio once", "locID": "STR_REP_INFO_TROPHIE_1"},
	"STR_REP_INFO_TROPHIE_3": {"value": "Perform 10 acrobatics", "locID": "STR_REP_INFO_TROPHIE_1"},
	"STR_REP_INFO_TROPHIE_2": {"value": "Travel 3000 m in a run", "locID": "STR_REP_INFO_TROPHIE_1"},
	"STR_REP_INFO_TROPHIE_1": {"value": "Defeat 100 enemies", "locID": "STR_REP_INFO_TROPHIE_1"},
	"STR_REP_NAME_TROPHIE_6": {"value": "Mysterio Solved", "locID": "STR_REP_NAME_TROPHIE_1"},
	"STR_REP_NAME_TROPHIE_5": {"value": "Amazing Combo-Man", "locID": "STR_REP_NAME_TROPHIE_1"},
	"STR_REP_NAME_TROPHIE_4": {"value": "Friendly Neighborhood", "locID": "STR_REP_NAME_TROPHIE_1"},
	"STR_REP_NAME_TROPHIE_3": {"value": "Stylish Arachnid", "locID": "STR_REP_NAME_TROPHIE_1"},
	"STR_REP_NAME_TROPHIE_2": {"value": "Going the Distance", "locID": "STR_REP_NAME_TROPHIE_1"},
	"STR_REP_NAME_TROPHIE_1": {"value": "Tough Spider", "locID": "STR_REP_NAME_TROPHIE_1"},
	"STR_REP_NAME_MISSION_1": {"value": "Defeat # enemies in one run", "locID": "STR_REP_NAME_MISSION_1"},
	"STR_REP_NAME_MISSION_2": {"value": "Travel #m in one run", "locID": "STR_REP_NAME_MISSION_1"},
	"STR_REP_NAME_MISSION_3": {"value": "Pass through a ring", "locID": "STR_REP_NAME_MISSION_1"},
	"STR_REP_NAME_MISSION_4": {"value": "Bounce on # enemies", "locID": "STR_REP_NAME_MISSION_1"},
	"STR_REP_NAME_MISSION_5": {"value": "Rack up a # combo", "locID": "STR_REP_NAME_MISSION_1"},
	"STR_REP_NAME_MISSION_6": {"value": "Grab # Spidey coins in one run", "locID": "STR_REP_NAME_MISSION_1"},
	"STR_REP_NAME_MISSION_7": {"value": "Perform # acrobatic", "locID": "STR_REP_NAME_MISSION_1"},
	"STR_REP_NAME_MISSION_8": {"value": "Defeat # enemies", "locID": "STR_REP_NAME_MISSION_1"},
	"STR_REP_NAME_MISSION_9": {"value": "Travel #m in one run", "locID": "STR_REP_NAME_MISSION_1"},
	"STR_REP_NAME_MISSION_10": {"value": "Grab onto a glider drone", "locID": "STR_REP_NAME_MISSION_1"},
	"STR_REP_NAME_MISSION_11": {"value": "Get # coins in total", "locID": "STR_REP_NAME_MISSION_1"},
	"STR_REP_NAME_MISSION_12": {"value": "Bounce on # enemies", "locID": "STR_REP_NAME_MISSION_1"},
	"STR_REP_NAME_MISSION_13": {"value": "Pass through # rings in one run", "locID": "STR_REP_NAME_MISSION_1"},
	"STR_REP_NAME_MISSION_14": {"value": "Perform # acrobatics", "locID": "STR_REP_NAME_MISSION_1"},
	"STR_REP_NAME_MISSION_15": {"value": "Travel #m in one run", "locID": "STR_REP_NAME_MISSION_1"},
	"STR_REP_NAME_MISSION_16": {"value": "Rack up a # combo", "locID": "STR_REP_NAME_MISSION_1"},
	"STR_REP_NAME_MISSION_17": {"value": "Grab # Spidey coins in one run", "locID": "STR_REP_NAME_MISSION_1"},
	"STR_REP_NAME_MISSION_18": {"value": "Defeat # enemies in one run", "locID": "STR_REP_NAME_MISSION_1"},
	"STR_REP_NAME_MISSION_19": {"value": "Pass through # rings", "locID": "STR_REP_NAME_MISSION_1"},
	"STR_REP_NAME_MISSION_20": {"value": "Travel #m without getting hit", "locID": "STR_REP_NAME_MISSION_1"},
	"STR_REP_NAME_MISSION_21": {"value": "Perform # acrobatics in one run", "locID": "STR_REP_NAME_MISSION_1"},
	"STR_REP_NAME_MISSION_22": {"value": "Rack up a # combo", "locID": "STR_REP_NAME_MISSION_1"},
	"STR_REP_NAME_MISSION_23": {"value": "Pass through # rings in one run", "locID": "STR_REP_NAME_MISSION_1"},
	"STR_REP_NAME_MISSION_24": {"value": "Defeat # enemies in one run", "locID": "STR_REP_NAME_MISSION_1"},
	"STR_REP_NAME_MISSION_25": {"value": "Travel #m in one run", "locID": "STR_REP_NAME_MISSION_1"},
	"STR_REP_ENDRUN_TOTAL_MISSIONS": {"value": "# / & MISSIONS COMPLETED", "locID": "STR_REP_ENDRUN_TOTAL_MISSIONS"},
	"STR_REP_ENDRUN_ALL_MISSIONS": {"value": "ALL MISSIONS COMPLETED", "locID": "STR_REP_ENDRUN_TOTAL_MISSIONS"},
	"STR_REP_MISSIONS_COMPLETED": {"value": "MISSION COMPLETE!", "locID": "STR_REP_MISSIONS_COMPLETED"},
	"STR_REP_END_RUN_DISTANCE": {"value": "DISTANCE", "locID": ""},
	"STR_REP_END_RUN_DISTANCE_DATA": {"value": "# m", "locID": ""},
	"STR_REP_END_RUN_MAX_RECORD_NUMBER": {"value": "# m", "locID": ""},
	"STR_REP_END_RUN_MAX_RECORD": {"value": "MAX RECORD ", "locID": ""},
	"STR_REP_END_RUN_NEW_RECORD": {"value": "NEW RECORD!", "locID": ""},
	"STR_REP_END_RUN_COINS": {"value": "COINS", "locID": "STR_REP_END_RUN_COINS"},
	"STR_REP_END_RUN_TITTLE_1": {"value": "TRY AGAIN", "locID": "STR_REP_END_RUN_TITTLE_1"},
	"STR_REP_END_RUN_TITTLE_2": {"value": "GOOD JOB!", "locID": "STR_REP_END_RUN_TITTLE_1"},
	"STR_REP_END_RUN_TITTLE_3": {"value": "GREAT!!", "locID": "STR_REP_END_RUN_TITTLE_1"},
	"STR_REP_END_RUN_TITTLE_4": {"value": "AMAZING!!!", "locID": "STR_REP_END_RUN_TITTLE_1"},
	"STR_REP_PAUSE_TITLE": {"value": "PAUSE", "locID": ""},
	"STR_REP_PAUSE_ALL_MISSIONS_CLEARED": {"value": "ALL MISSIONS CLEARED!", "locID": ""},
	"STR_REP_SCREENS_SHOP_MAXED_OUT": {"value": "MAXED OUT", "locID": ""},
	"STR_REP_SHOP_COST": {"value": "COST", "locID": ""},
	"STR_REP_SHOP_BUTTON": {"value": "#", "locID": ""},
	"STR_REP_CUTSCENE_INFO_1": {"value": "The city is under total chaos thanks to me: Mysterio!", "locID": "STR_REP_CUTSCENE_INFO_1"},
	"STR_REP_CUTSCENE_INFO_2": {"value": "Spider-Man, if you want this to stop come and get me... if you can!", "locID": "STR_REP_CUTSCENE_INFO_1"},
	"STR_REP_CUTSCENE_INFO_3": {"value": "As you wish, bubble head. Here comes Spider-Man!", "locID": "STR_REP_CUTSCENE_INFO_1"},
	"STR_REP_CUTSCENE_INFO_4": {"value": "Well NYC, you can rest well, the illusions are gone and Beck is on his way back to prison again!", "locID": "STR_REP_CUTSCENE_INFO_1"},
	"STR_REP_CUTSCENE_INFO_5": {"value": "Courtesy of your friendly neighborhood Spider-Man!", "locID": "STR_REP_CUTSCENE_INFO_1"},
	"STR_REP_CUTSCENE_INFO_6": {"value": "Oh Spidey, but you don't know...", "locID": "STR_REP_CUTSCENE_INFO_1"},
	"STR_REP_CUTSCENE_INFO_7": {"value": "Maybe all of this is still... an illusion...", "locID": "STR_REP_CUTSCENE_INFO_1"}
};
