window['swt_ui'] = window['swt_ui'].concat([
	{
		"string": "STR_REP_CREDITS_INFO_2",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "700",
		"height": "80",
		"size_ltr": "28",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangLlamaGenialGordis",
		"size_rtl": "28",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangLlamaGenialGordis",
		"gui": "mcGuiScreenCredits",
		"control": "mcGuiTextInfo_2",
		"type": "text"
	},
	{
		"string": "STR_REP_CREDITS_INFO_1",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "700",
		"height": "80",
		"size_ltr": "28",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangLlamaGenialGordis",
		"size_rtl": "28",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangLlamaGenialGordis",
		"gui": "mcGuiScreenCredits",
		"control": "mcGuiTextInfo_1",
		"type": "text"
	},
	{
		"string": "STR_REP_CREDITS_TITLE",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "335",
		"height": "70",
		"size_ltr": "76",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "76",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiScreenCredits",
		"control": "mcGuiTextTitleS",
		"type": "text"
	},
	{
		"string": "STR_REP_CREDITS_TITLE",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "335",
		"height": "70",
		"size_ltr": "76",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "76",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiScreenCredits",
		"control": "mcGuiTextTitle",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_CONFIRM_INFORMATION",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "255",
		"height": "35",
		"size_ltr": "40",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangLlamaGenialGordis",
		"size_rtl": "40",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangLlamaGenialGordis",
		"gui": "mcGuiPopupsConfirm",
		"control": "mcGuiTxtQuestion_s",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_CONFIRM_INFORMATION",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "255",
		"height": "35",
		"size_ltr": "40",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangLlamaGenialGordis",
		"size_rtl": "40",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangLlamaGenialGordis",
		"gui": "mcGuiPopupsConfirm",
		"control": "mcGuiTxtQuestion",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_CONFIRM_TITLE",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "335",
		"height": "70",
		"size_ltr": "76",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "76",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiPopupsConfirm",
		"control": "mcGuiTxtTittle_s",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_CONFIRM_TITLE",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "335",
		"height": "70",
		"size_ltr": "76",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "76",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiPopupsConfirm",
		"control": "mcGuiTxtTittle",
		"type": "text"
	},
	{
		"string": "STR_REP_CUTSCENE_INFO_1",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "600",
		"height": "120",
		"size_ltr": "24",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangLlamaGenialGordis",
		"size_rtl": "24",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangLlamaGenialGordis",
		"gui": "mcGuiScreenCutscene",
		"control": "mcGuiTxt",
		"type": "text"
	},
	{
		"string": "STR_REP_TROPHIES_TITLE",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "335",
		"height": "70",
		"size_ltr": "76",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "76",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiScreenTrophies",
		"control": "mcGuiTxtTitleS",
		"type": "text"
	},
	{
		"string": "STR_REP_TROPHIES_TITLE",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "335",
		"height": "70",
		"size_ltr": "76",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "76",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiScreenTrophies",
		"control": "mcGuiTxtTitle",
		"type": "text"
	},
	{
		"string": "STR_REP_NAME_TROPHIE_1",
		"color": "#000031",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "335",
		"height": "70",
		"size_ltr": "40",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "40",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiScreenTrophies",
		"control": "mcGuiTxtTrophieTitle_s",
		"type": "text"
	},
	{
		"string": "STR_REP_NAME_TROPHIE_1",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "335",
		"height": "70",
		"size_ltr": "40",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "40",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiScreenTrophies",
		"control": "mcGuiTxtTrophieTitle",
		"type": "text"
	},
	{
		"string": "STR_REP_INFO_TROPHIE_1",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "400",
		"height": "100",
		"size_ltr": "24",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangLlamaGenialGordis",
		"size_rtl": "24",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangLlamaGenialGordis",
		"gui": "mcGuiScreenTrophies",
		"control": "mcGuiTxtTrophieInfo",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_ENDGAME_TEXT",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "550",
		"height": "100",
		"size_ltr": "36",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangLlamaGenialGordis",
		"size_rtl": "36",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangLlamaGenialGordis",
		"gui": "mcGuiScreenEndGame",
		"control": "mcGuiTxtText_s",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_ENDGAME_TEXT",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "550",
		"height": "100",
		"size_ltr": "36",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangLlamaGenialGordis",
		"size_rtl": "36",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangLlamaGenialGordis",
		"gui": "mcGuiScreenEndGame",
		"control": "mcGuiTxtText",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_ENDGAME_TITLE",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "700",
		"height": "100",
		"size_ltr": "130",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "130",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiScreenEndGame",
		"control": "mcGuiTxtTittle_s",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_ENDGAME_TITLE",
		"color": "#ffff00",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "700",
		"height": "100",
		"size_ltr": "130",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "130",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiScreenEndGame",
		"control": "mcGuiTxtTittle",
		"type": "text"
	},
	{
		"string": "STR_REP_SCREENS_SHOP_UPGRADE_TITLE_1",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "300",
		"height": "70",
		"size_ltr": "40",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "40",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiScreenShop",
		"control": "mcGuiTxtShopTitle",
		"type": "text"
	},
	{
		"string": "STR_REP_SCREENS_SHOP_UPGRADE_INFO_1",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "320",
		"height": "140",
		"size_ltr": "22",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangLlamaGenialGordis",
		"size_rtl": "22",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangLlamaGenialGordis",
		"gui": "mcGuiScreenShop",
		"control": "mcGuiTxtShopInfo",
		"type": "text"
	},
	{
		"string": "STR_REP_SHOP_COST",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "300",
		"height": "50",
		"size_ltr": "45",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "45",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiScreenShop",
		"control": "mcGuiTxtShopCost",
		"type": "text"
	},
	{
		"string": "STR_REP_END_RUN_COINS",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "240",
		"height": "35",
		"size_ltr": "40",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "40",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiScreenShop",
		"control": "mcGuiTxtCoins",
		"type": "text"
	},
	{
		"string": "STR_REP_HUD_COINS_DATA",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "100",
		"height": "35",
		"size_ltr": "40",
		"hAlign_ltr": "right",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "40",
		"hAlign_rtl": "right",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiScreenShop",
		"control": "mcGuiTxtCoinsNumber",
		"type": "text"
	},
	{
		"string": "STR_REP_SHOP_TITLE",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "335",
		"height": "70",
		"size_ltr": "76",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "76",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiScreenShop",
		"control": "mcGuiTxtTitle_s",
		"type": "text"
	},
	{
		"string": "STR_REP_SHOP_TITLE",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "335",
		"height": "70",
		"size_ltr": "76",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "76",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiScreenShop",
		"control": "mcGuiTxtTitle",
		"type": "text"
	},
	{
		"string": "STR_REP_DIALOGUE_TAP",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "700",
		"height": "70",
		"size_ltr": "24",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangLlamaGenialGordis",
		"size_rtl": "24",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangLlamaGenialGordis",
		"gui": "mcGuiPopupsTutorial",
		"control": "mcGuiTextTap",
		"type": "text"
	},
	{
		"string": "STR_REP_TUTORIAL_INFO_1",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "550",
		"height": "150",
		"size_ltr": "25",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangLlamaGenialGordis",
		"size_rtl": "25",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangLlamaGenialGordis",
		"gui": "mcGuiPopupsTutorial",
		"control": "mcGuiTxtInfo",
		"type": "text"
	},
	{
		"string": "STR_REP_PAUSE_ALL_MISSIONS_CLEARED",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "500",
		"height": "80",
		"size_ltr": "70",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "70",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiPopupsPause",
		"control": "mcGuiTxtMissionsClearedS",
		"type": "text"
	},
	{
		"string": "STR_REP_PAUSE_ALL_MISSIONS_CLEARED",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "500",
		"height": "80",
		"size_ltr": "70",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "70",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiPopupsPause",
		"control": "mcGuiTxtMissionsCleared",
		"type": "text"
	},
	{
		"string": "STR_REP_PAUSE_TITLE",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "340",
		"height": "80",
		"size_ltr": "76",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "76",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiPopupsPause",
		"control": "mcGuiTxtTittle_s",
		"type": "text"
	},
	{
		"string": "STR_REP_PAUSE_TITLE",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "340",
		"height": "80",
		"size_ltr": "76",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "76",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiPopupsPause",
		"control": "mcGuiTxtTittle",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_MISSIONS",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "340",
		"height": "80",
		"size_ltr": "80",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "80",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiPopupsMissions",
		"control": "mcGuiTxtTittle_s",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_MISSIONS",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "340",
		"height": "80",
		"size_ltr": "80",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "80",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiPopupsMissions",
		"control": "mcGuiTxtTittle",
		"type": "text"
	},
	{
		"string": "STR_REP_TUTORIAL_INFO_1",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "400",
		"height": "150",
		"size_ltr": "25",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangLlamaGenialGordis",
		"size_rtl": "25",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangLlamaGenialGordis",
		"gui": "mcGuiPopupsHelp",
		"control": "mcGuiTxtInfo",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_HELP_VERSION",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "600",
		"height": "50",
		"size_ltr": "36",
		"hAlign_ltr": "right",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "36",
		"hAlign_rtl": "right",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiPopupsHelp",
		"control": "mcGuiTxtVersion",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_HELP_TITLE",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "340",
		"height": "80",
		"size_ltr": "80",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "80",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiPopupsHelp",
		"control": "mcGuiTxtTittle_s",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_HELP_TITLE",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "340",
		"height": "80",
		"size_ltr": "80",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "80",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiPopupsHelp",
		"control": "mcGuiTxtTittle",
		"type": "text"
	},
	{
		"string": "STR_REP_END_RUN_COINS",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "150",
		"height": "35",
		"size_ltr": "40",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "40",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiPopupsEndRun2",
		"control": "mcGuiTxtCoins",
		"type": "text"
	},
	{
		"string": "STR_REP_HUD_COINS_DATA",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "100",
		"height": "35",
		"size_ltr": "40",
		"hAlign_ltr": "right",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "40",
		"hAlign_rtl": "right",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiPopupsEndRun2",
		"control": "mcGuiTxtCoinsNumber",
		"type": "text"
	},
	{
		"string": "STR_REP_END_RUN_DISTANCE",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "300",
		"height": "35",
		"size_ltr": "42",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "42",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiPopupsEndRun2",
		"control": "mcGuiTxtDistance_s",
		"type": "text"
	},
	{
		"string": "STR_REP_END_RUN_DISTANCE",
		"color": "#ffff00",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "300",
		"height": "35",
		"size_ltr": "42",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "42",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiPopupsEndRun2",
		"control": "mcGuiTxtDistance",
		"type": "text"
	},
	{
		"string": "STR_REP_END_RUN_DISTANCE_DATA",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "320",
		"height": "80",
		"size_ltr": "110",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "110",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiPopupsEndRun2",
		"control": "mcGuiTxtScore_s",
		"type": "text"
	},
	{
		"string": "STR_REP_END_RUN_DISTANCE_DATA",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "320",
		"height": "80",
		"size_ltr": "110",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "110",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiPopupsEndRun2",
		"control": "mcGuiTxtScore",
		"type": "text"
	},
	{
		"string": "STR_REP_END_RUN_TITTLE_1",
		"color": "#e4002b",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "550",
		"height": "100",
		"size_ltr": "100",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "100",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiPopupsEndRun2",
		"control": "mcGuiTxtTitle_s",
		"type": "text"
	},
	{
		"string": "STR_REP_END_RUN_TITTLE_1",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "550",
		"height": "100",
		"size_ltr": "100",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "100",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiPopupsEndRun2",
		"control": "mcGuiTxtTitle",
		"type": "text"
	},
	{
		"string": "STR_REP_END_RUN_TITTLE_1",
		"color": "#e4002b",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "550",
		"height": "100",
		"size_ltr": "100",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "100",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiPopupsEndRun1",
		"control": "mcGuiTxtTitle_s",
		"type": "text"
	},
	{
		"string": "STR_REP_END_RUN_TITTLE_1",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "550",
		"height": "100",
		"size_ltr": "100",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "100",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiPopupsEndRun1",
		"control": "mcGuiTxtTitle",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_CHEATS_COINS",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "300",
		"height": "35",
		"size_ltr": "25",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangLlamaGenialGordis",
		"size_rtl": "25",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangLlamaGenialGordis",
		"gui": "mcGuiPopupsCheats",
		"control": "mcGuiText_coins",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_CHEATS_M_3",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "300",
		"height": "35",
		"size_ltr": "25",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangLlamaGenialGordis",
		"size_rtl": "25",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangLlamaGenialGordis",
		"gui": "mcGuiPopupsCheats",
		"control": "mcGuiTextM_3",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_CHEATS_M_2",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "300",
		"height": "35",
		"size_ltr": "25",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangLlamaGenialGordis",
		"size_rtl": "25",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangLlamaGenialGordis",
		"gui": "mcGuiPopupsCheats",
		"control": "mcGuiTextM_2",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_CHEATS_M_1",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "300",
		"height": "35",
		"size_ltr": "25",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangLlamaGenialGordis",
		"size_rtl": "25",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangLlamaGenialGordis",
		"gui": "mcGuiPopupsCheats",
		"control": "mcGuiTextM_1",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_CHEATS",
		"color": "#e4002b",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "550",
		"height": "100",
		"size_ltr": "100",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "100",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiPopupsCheats",
		"control": "mcGuiTxtTitle_s",
		"type": "text"
	},
	{
		"string": "STR_REP_POPUP_CHEATS",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "550",
		"height": "100",
		"size_ltr": "100",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "100",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiPopupsCheats",
		"control": "mcGuiTxtTitle",
		"type": "text"
	},
	{
		"string": "STR_REP_NAME_TROPHIE_1",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "560",
		"height": "70",
		"size_ltr": "24",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangLlamaGenialGordis",
		"size_rtl": "24",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangLlamaGenialGordis",
		"gui": "mcGuiPanelTrophy",
		"control": "mcGuiTextInfo",
		"type": "text"
	},
	{
		"string": "STR_REP_PANEL_TROPHIE_ACHIEVEMENT",
		"color": "#000000",
		"vAlign": "top",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "300",
		"height": "50",
		"size_ltr": "42",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "42",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiPanelTrophy",
		"control": "mcGuiTextTtile_s",
		"type": "text"
	},
	{
		"string": "STR_REP_PANEL_TROPHIE_ACHIEVEMENT",
		"color": "#ffffff",
		"vAlign": "top",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "300",
		"height": "50",
		"size_ltr": "42",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "42",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiPanelTrophy",
		"control": "mcGuiTextTtile",
		"type": "text"
	},
	{
		"string": "STR_REP_DIALOGUE_NAME02",
		"color": "#000000",
		"vAlign": "top",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "42",
		"hAlign_ltr": "right",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "42",
		"hAlign_rtl": "right",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiDialog",
		"control": "mcGuiTextName02_s",
		"type": "text"
	},
	{
		"string": "STR_REP_DIALOGUE_NAME02",
		"color": "#ffffff",
		"vAlign": "top",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "42",
		"hAlign_ltr": "right",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "42",
		"hAlign_rtl": "right",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiDialog",
		"control": "mcGuiTextName02",
		"type": "text"
	},
	{
		"string": "STR_REP_DIALOGUE_NAME01",
		"color": "#000000",
		"vAlign": "top",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "42",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "42",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiDialog",
		"control": "mcGuiTextName01_s",
		"type": "text"
	},
	{
		"string": "STR_REP_DIALOGUE_NAME01",
		"color": "#ffffff",
		"vAlign": "top",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "42",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "42",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiDialog",
		"control": "mcGuiTextName01",
		"type": "text"
	},
	{
		"string": "STR_REP_DIALOGUE_INFO_1",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "600",
		"height": "70",
		"size_ltr": "24",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangLlamaGenialGordis",
		"size_rtl": "24",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangLlamaGenialGordis",
		"gui": "mcGuiDialog",
		"control": "mcGuiTextDialogue",
		"type": "text"
	},
	{
		"string": "STR_REP_DIALOGUE_TAP",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "700",
		"height": "70",
		"size_ltr": "24",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangLlamaGenialGordis",
		"size_rtl": "24",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangLlamaGenialGordis",
		"gui": "mcGuiDialog",
		"control": "mcGuiTextTap",
		"type": "text"
	},
	{
		"string": "STR_REP_HUD_NEW_RECORD",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "200",
		"height": "100",
		"size_ltr": "112",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "112",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiNewRecord",
		"control": "mcGuiTextNewRecord_s",
		"type": "text"
	},
	{
		"string": "STR_REP_HUD_NEW_RECORD",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "200",
		"height": "100",
		"size_ltr": "112",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "112",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiNewRecord",
		"control": "mcGuiTextNewRecord",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_3",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "200",
		"height": "100",
		"size_ltr": "112",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "112",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiGo",
		"control": "mcGuiTextNumber01_s",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_3",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "200",
		"height": "100",
		"size_ltr": "112",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "112",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiGo",
		"control": "mcGuiTextNumber01",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_2",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "200",
		"height": "100",
		"size_ltr": "112",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "112",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiGo",
		"control": "mcGuiTextNumber02_s",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_2",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "200",
		"height": "100",
		"size_ltr": "112",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "112",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiGo",
		"control": "mcGuiTextNumber02",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_1",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "200",
		"height": "100",
		"size_ltr": "112",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "112",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiGo",
		"control": "mcGuiTextNumber03_s",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_1",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "200",
		"height": "100",
		"size_ltr": "112",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "112",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiGo",
		"control": "mcGuiTextNumber03",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_GO",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "200",
		"height": "100",
		"size_ltr": "112",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "112",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiGo",
		"control": "mcGuiTextGo_s",
		"type": "text"
	},
	{
		"string": "STR_REP_MESSAGE_GO",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "200",
		"height": "100",
		"size_ltr": "112",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "112",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiGo",
		"control": "mcGuiTextGo",
		"type": "text"
	},
	{
		"string": "STR_REP_HUD_COMBO_HIT",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "200",
		"height": "100",
		"size_ltr": "48",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "48",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiCombo",
		"control": "mcGuiTextHit_s",
		"type": "text"
	},
	{
		"string": "STR_REP_HUD_COMBO_HIT",
		"color": "#e4002b",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "200",
		"height": "100",
		"size_ltr": "48",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "48",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiCombo",
		"control": "mcGuiTextHit",
		"type": "text"
	},
	{
		"string": "STR_REP_HUD_COINS_DATA",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "200",
		"height": "100",
		"size_ltr": "112",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "112",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiCombo",
		"control": "mcGuiTextCombo_s",
		"type": "text"
	},
	{
		"string": "STR_REP_HUD_COINS_DATA",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "200",
		"height": "100",
		"size_ltr": "112",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "112",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiCombo",
		"control": "mcGuiTextCombo",
		"type": "text"
	},
	{
		"string": "STR_REP_NAME_MISSION_1",
		"color": "#545454",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "365",
		"height": "45",
		"size_ltr": "20",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangLlamaGenialGordis",
		"size_rtl": "20",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangLlamaGenialGordis",
		"gui": "mcGuiMissionProgress",
		"control": "mcGuiTextMission",
		"type": "text"
	},
	{
		"string": "STR_REP_MISSIONS_COMPLETED",
		"color": "#ff0000",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "280",
		"height": "20",
		"size_ltr": "26",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "26",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiMissionProgress",
		"control": "mcGuiTextCompleted",
		"type": "text"
	},
	{
		"string": "STR_REP_NAME_MISSION_1",
		"color": "#545454",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "400",
		"height": "35",
		"size_ltr": "24",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangLlamaGenialGordis",
		"size_rtl": "24",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangLlamaGenialGordis",
		"gui": "mcGuiContentMission",
		"control": "mcGuiTextMission",
		"type": "text"
	},
	{
		"string": "STR_REP_END_RUN_MAX_RECORD",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "200",
		"height": "35",
		"size_ltr": "32",
		"hAlign_ltr": "left",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "32",
		"hAlign_rtl": "left",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiContentMaxRecord",
		"control": "mcGuiTxtMaxRecord",
		"type": "text"
	},
	{
		"string": "STR_REP_END_RUN_NEW_RECORD",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "200",
		"height": "35",
		"size_ltr": "40",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "40",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiContentMaxRecord",
		"control": "mcGuiTxtNewRecord",
		"type": "text"
	},
	{
		"string": "STR_REP_END_RUN_MAX_RECORD_NUMBER",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "200",
		"height": "35",
		"size_ltr": "32",
		"hAlign_ltr": "right",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "32",
		"hAlign_rtl": "right",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiContentMaxRecord",
		"control": "mcGuiTxtMaxRecordNumber",
		"type": "text"
	},
	{
		"string": "STR_REP_SHOP_BUTTON",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "200",
		"height": "60",
		"size_ltr": "50",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "50",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiContentBuy",
		"control": "mcGuiTextPrice",
		"type": "text"
	},
	{
		"string": "STR_REP_SCREENS_SHOP_MAXED_OUT",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "1",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "200",
		"height": "100",
		"size_ltr": "60",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "60",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiContentBuy",
		"control": "mcGuiMaxedOut",
		"type": "text"
	},
	{
		"string": "STR_REP_ENDRUN_TOTAL_MISSIONS",
		"color": "#ff0000",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "460",
		"height": "35",
		"size_ltr": "40",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "40",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiContentBar",
		"control": "mcGuiTextInfo",
		"type": "text"
	},
	{
		"string": "STR_REP_HUD_COINS_DATA",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "115",
		"height": "35",
		"size_ltr": "40",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "40",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiHUD",
		"control": "mcGuiTxtCoins",
		"type": "text"
	},
	{
		"string": "STR_REP_HUD_DISTANCE_DATA",
		"color": "#000000",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "140",
		"height": "35",
		"size_ltr": "40",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "40",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiHUD",
		"control": "mcGuiTxtDistance",
		"type": "text"
	},
	{
		"string": "STR_REP_LOADING_PRELOAD_FONT_4",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "20",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangLlamaGenialGordis",
		"size_rtl": "20",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangLlamaGenialGordis",
		"gui": "mcGuiScreenLoader",
		"control": "mcGuiPreloadFont4",
		"type": "text"
	},
	{
		"string": "STR_REP_LOADING_PRELOAD_FONT_3",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "20",
		"hAlign_ltr": "center",
		"font_ltr": "BamtangGuacamayoTitularGordis",
		"size_rtl": "20",
		"hAlign_rtl": "center",
		"font_rtl": "BamtangGuacamayoTitularGordis",
		"gui": "mcGuiScreenLoader",
		"control": "mcGuiPreloadFont3",
		"type": "text"
	},
	{
		"string": "STR_REP_LOADING_PRELOAD_FONT_2",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "20",
		"hAlign_ltr": "center",
		"font_ltr": "bamtangviscachatitulargordisRg",
		"size_rtl": "20",
		"hAlign_rtl": "center",
		"font_rtl": "bamtangviscachatitulargordisRg",
		"gui": "mcGuiScreenLoader",
		"control": "mcGuiPreloadFont2",
		"type": "text"
	},
	{
		"string": "STR_REP_LOADING_PRELOAD_FONT_1",
		"color": "#ffffff",
		"vAlign": "center",
		"wordWrap": "0",
		"hRelative": "0",
		"vRelative": "0",
		"ignoreArea": "0",
		"width": "165",
		"height": "35",
		"size_ltr": "20",
		"hAlign_ltr": "center",
		"font_ltr": "arialbold",
		"size_rtl": "20",
		"hAlign_rtl": "center",
		"font_rtl": "arialbold",
		"gui": "mcGuiScreenLoader",
		"control": "mcGuiPreloadFont1",
		"type": "text"
	}
]);
